# Generated by Django 4.1.6 on 2023-02-01 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('schedule', models.CharField(max_length=100)),
                ('students', models.ManyToManyField(to='academic.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.teacher')),
            ],
        ),
    ]
