# Generated by Django 4.1.6 on 2023-02-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='class_taught',
            field=models.ManyToManyField(related_name='teachers', to='academic.class'),
        ),
    ]
